repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-yaml
  - id: detect-private-key

- repo: local
  hooks:
  - id: isort
    name: sort import statements
    entry: poetry run isort
    language: system
    types: [python]
  - id: docformatter
    name: format docstrings
    entry: poetry run docformatter --pre-summary-newline --make-summary-multi-line --in-place
    language: system
    types: [python]
  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    types: [python]
